#!/bin/bash 

 

while [[ $# -gt 0 ]]; do 

    key="$1" 

    case $key in 

        --logs) 

            logs_flag=true 

            ;; 

        *) 

            echo "Nieznana opcja: $key" 

            exit 1 

            ;; 

    esac 

    shift 

done 

 

if [ "$logs_flag" = true ]; then 

    for ((i=1; i<=100; i++)); do 

        nazwa_pliku="log${i}.txt" 

        dzisiaj=$(date +"%Y-%m-%d") 

        echo "Nazwa pliku: $nazwa_pliku" > "$nazwa_pliku" 

        echo "Nazwa skryptu: logs.sh" >> "$nazwa_pliku" 

        echo "Data utworzenia: $dzisiaj" >> "$nazwa_pliku" 

    done 

fi 
